---
apiVersion: v1
kind: Namespace
metadata:
  name: newrelic
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: newrelic
  namespace: newrelic
spec:
  interval: 1m
  url: https://helm-charts.newrelic.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: newrelic
  namespace: newrelic
spec:
  interval: 5m
  chart:
    spec:
      chart: newrelic/nri-bundle
      version: 5.0.107
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: newrelic
      interval: 1m
      valuesFrom:
        - kind: ConfigMap
          name: newrelic
        - kind: Secret
          name: newrelic
  releaseName: newrelic-bundle
  values:
    replicaCount: 1
