apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux
  namespace: poc
  labels:
    app: webflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webflux
  template:
    metadata:
      labels:
        app: webflux
    spec:
      serviceAccountName: poc-user
      volumes:
        - name: secrets
          secret:
            secretName: secrets
      containers:
        - name: webflux
          image: ghcr.io/tamamico/poc-webflux-native:0.0.1-SNAPSHOT
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "1G"
              cpu: "500m"
              ephemeral-storage: "512M"
            limits:
              memory: "4G"
              cpu: "1"
              ephemeral-storage: "1G"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: secrets
              readOnly: true
              mountPath: /etc/secrets/poc
          env:
            - name: OTEL_INSTRUMENTATION_COMMON_DEFAULT_ENABLED
              value: 'true'
            - name: OTEL_JAVA_GLOBAL_AUTOCONFIGURE_ENABLED
              value: 'true'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: https://otlp.eu01.nr-data.net:4317
            - name: OTEL_EXPORTER_OTLP_HEADERS
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: newrelic.api-key
---
apiVersion: v1
kind: Service
metadata:
  name: webflux-service
  namespace: poc
spec:
  selector:
    app: webflux
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webflux-ingress
  namespace: poc
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: kubernetes.docker.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: webflux-service
                port:
                  number: 80
