name: Update infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/terraform/**'
      - 'infrastructure/confluent/**'
      - 'main-infrastructure.yml'
      - '.github/actions/terraform/action.yml'
  workflow_dispatch:

jobs:
  sonar:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run SonarCloud analysis
        uses: sonarsource/sonarqube-scan-action@v5.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./infrastructure
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
  update-terraform:
    name: Update Terraform Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Set-up Confluent Cloud workspace in Terraform Cloud
        uses: ./.github/actions/terraform
        with:
          provider: terraform
          resource: workspaces
          token: ${{ secrets.TFE_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
      - name: Set-up staging environment in Confluent Cloud
        uses: ./.github/actions/terraform
        with:
          provider: confluent
          resource: environment
          token: ${{ secrets.TFE_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
      - name: Set-up teams workspaces in Terraform Cloud
        uses: ./.github/actions/terraform
        with:
          provider: terraform
          resource: teams
          token: ${{ secrets.TFE_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
