name: Update Terraform Cloud infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'infrastructure/terraform/**'
      - '.github/workflows/main-infra-terraform.yml'
      - '.github/actions/terraform/action.yml'
  workflow_dispatch:

jobs:
  sonar:
    name: Run SonarCloud analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run SonarCloud analysis
        uses: sonarsource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: ./infrastructure
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
  update-terraform:
    name: Update Terraform Cloud infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'
      - name: Set-up "environment" workspace
        uses: ./.github/actions/terraform
        with:
          provider: terraform
          resource: workspaces
          token: ${{ secrets.TFE_TOKEN }}
          organization: ${{ vars.TF_CLOUD_ORGANIZATION }}
